language: node_js
node_js:
  - 8.10.0
script:
  - npm run lint
  - npm run coverage
cache:
  directories:
  - node_modules
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"